# Generated by Django 3.1.5 on 2021-01-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.FileField(upload_to='')),
            ],
        ),
    ]
